= 読書について

:lang: ja
:doctype: article
// :toc: left
// :toclevels: 3
// :toc-title: 目次
:chapter-label:
// :sectnums:

== 技術書の読書法
読書の技術も1つのスキルと捉えます。技術書は小説などと違い、楽しむためのものではなく、自らが得るものという目的を持って読むものです。そのためただ単純に読むのではなく、技術をもって効果的に読む必要があります。
そのためには、まず読書をする前に準備し、読書後どのようにするか計画を持って読む必要があります。

=== 準備編
==== 読書前の心構えについて
読書をする前には以下の心構えを持って読書を開始することが重要です。

* 目的を持って読む
* 一字一句全部を読もうとしない
* 暗記しようとしない

この心構えを忘れて読書をすると、目的ないままだらだらと読んでしまうことになる。そして本来必要のない部分に時間をかけてしまい、無駄に時間がかかったり、最悪本来の目的を達成しないことになりかねます。

==== 目的を持って読む
目的を設定せずに読み始めると、知りたい情報がなかなか得られないまま、関係ない部分を読まされ続けたり。読み終わっても結局得たかったものが得られなかったりする場合があります。本を読む前に目的を設定しましょう。そして目的のものが本のどこに書かれているか確認して読み始めます。

==== 一字一句読もうとしない
本は目的をもって読みます。そのため本に書いてある全てのことが知りたいことではないはずです（プログラミング言語の文法などが知りたい場合、リファレンス本の基本的な文法を全て読む場合もありますが、応用的な部分は読む必要ないでしょう）。

==== 暗記しようとしない
本を丸暗記する必要はありません。本を丸暗記して脳の中に入れることが目的ではなく、こんなことが書いてあったなということを理解することが目的であるからです。

[quote, ショーペンハウエル, 『読書について』]
____
読み終えたものをいっさい忘れまいと思うのは、食べたものをいっさい、
体内にとどめたいと願うようなものである。
____

本はあくまで外付けの記憶媒体です。そこに何が書かれてあり、どこにあるかを理解していれば必要な時にいつでも取り出せば良いのです。使用頻度の高いものだけを脳内のオンメモリに持ってくれば良いのです。

=== 読書編

==== 目次を読む
最初に目次をよく読みます。全体を通して書かれていることは何か、自分の興味のある部分はどこかを目次を読むことで把握します。全体を把握することで、どこから読むべきかの優先順位をつけて読む場所を決定することが出来ます。

==== 興味のある部分だけを読む
「通読しよう」「一字一句読もう」という読み方への強迫観念が読書の難易度を上げます。
技術書を読む目的は知識を得ることであり、通読して全てを読むことが目的ではありません。
読書は興味のある部分だけを読み、興味のない部分を読む必要はなないです。

==== つまらない場合は読むのをやめる
つまらない、自分のレベルと合っておらず得るものがないと判断した場合は読むのをやめた方が良いです。本の値段よりも得るものがないのに読んでいる時間のほうが無駄です。
一度つまらないと感じてしまった場合、読み進めるのも苦痛になり頭にも入ってきません。


=== 読後編

==== 本は2度読む
本は2度読む。もしくはまとめたものを再度見直す。
[quote, ショーペンハウエル, 『読書について』]
____
「反復は研究の母なり。」
重要な書物はいかなるものでも、二度読むべきである。
____

==== アウトプットする
読むだけで読んで得たものを活用しないのはたんなる読書好きでしかありません。得たものをアウトプットし活用することに目的があり。アウトプットし考えることにより定着していきます。

[quote, ショーペンハウエル, 『読書について』]
____
読書とは他人に考えてもらうことである。1日を多読に費やす勤勉な人間はしだいに自分でものを考える力を失っていく。
____


=== 参考文献
[bibliography]
- ショーペンハウエル[著]斎藤忍随[訳].『読書について』.岩波文庫
- 小林秀雄.『読書について』.中央公論社(2013)


=== 参考文献(未読)
- https://www.scienceshift.jp/blog/catalog-of-reading-techniques[読書の技術カタログ〜本を読むために知っておきたい知識・テクニック〜]

- https://scienceshift.jp/blog/how-to-acquire-knowledge-and-read-books-properly-01[東大「現代文」の知識を仕事に生かす〜知識を身につけ本をきちんと読む方法【相澤理氏連載：第一回】]
- https://scienceshift.jp/blog/how-to-acquire-knowledge-and-read-books-properly-02[東大「現代文」の知識を仕事に生かす〜「幅の広い指示語」を理解する【相澤理氏連載：第二回】]
- https://scienceshift.jp/blog/how-to-acquire-knowledge-and-read-books-properly-03[東大「現代文」の知識を仕事に生かす〜〈具体〉と〈抽象〉の関係をとらえる【相澤理氏連載：第三回】]
- https://scienceshift.jp/blog/reading-skills-seminar-01[「読む技術」養成講座【第一回：精読…きちんと正確に読む】国立国語研究所教授・石黒圭氏寄稿]
- https://scienceshift.jp/blog/reading-skills-seminar-02[「読む技術」養成講座【第二回：速読…さくさく素早く読む】国立国語研究所教授・石黒圭氏寄稿]
- https://scienceshift.jp/blog/reading-skills-seminar-03[「読む技術」養成講座【第三回：熟読…じっくり深く読む】国立国語研究所教授・石黒圭氏寄稿]




- https://opac.lib.city.yokohama.lg.jp/opac/OPP1500?ID=37&SELDATA=TOSHO&SEARCHID=1&START=31&ORDER=DESC&ORDER_ITEM=SORT4-F&LISTCNT=10&MAXCNT=1000&SEARCHMETHOD=DT_SEARCH&MENUNO=1[本を読めなくなった人のための読書論 若松英輔／著]
- https://opac.lib.city.yokohama.lg.jp/opac/OPP1500?ID=48&SELDATA=TOSHO&SEARCHID=1&START=41&ORDER=DESC&ORDER_ITEM=SORT4-F&LISTCNT=10&MAXCNT=1000&SEARCHMETHOD=DT_SEARCH&MENUNO=1[「すぐやる人」の読書術 塚本亮／著]