:lang: ja
:doctype: article
// :toc: left
// :toclevels: 3
// :toc-title: 目次
:chapter-label:
// :sectnums:

== 技術書の読書について
読書の技術も1つのスキルと捉えます。技術書は小説などと違い、楽しむためのものではなく、自らが得るものという目的を持って読むものです。そのためただ単純に読むのではなく、技術をもって効果的に読む必要があります。

=== 準備編
==== 読書前の心構えについて
読書をする前には以下の心構えを持って読書を開始することが重要です。

* 目的を持って読む
* 一字一句全部を読もうとしない
* 暗記しようとしない

==== 目的を持って読む
目的を設定せずに読み始めると、知りたい情報がなかなか得られないまま、関係ない部分を読まされ続けたり。読み終わっても結局得たかったものが得られなかったりする場合があります。本を読む前に目的を設定しましょう。そして目的のものが本のどこに書かれているか確認して読み始めます。

==== 一字一句読もうとしない
本は目的をもって読みます。そのため本に書いてある全てのことが知りたいことではないはずです（プログラミング言語の文法などが知りたい場合、リファレンス本の基本的な文法を全て読む場合もありますが、応用的な部分は読む必要ないでしょう）。

==== 暗記しようとしない
本を丸暗記する必要はありません。本を丸暗記して脳の中に入れることが目的ではなく、こんなことが書いてあったなということを理解することが目的であるからです。

[quote, ショーペンハウエル『読書について』]
____
読んだものをすべて覚えておきたがるのは、
食べたものをみな身体にとどめておきたがるようなものだ
____

本はあくまで外付けの記憶媒体です。そこに何が書かれてあり、どこにあるかを理解していれば必要な時にいつでも取り出せば良いのです。使用頻度の高いものだけを脳内のオンメモリに持ってくれば良いのです。

=== 読書編

==== 目次を読む
最初に目次をよく読みます。全体を通して書かれていることは何か、自分の興味のある部分はどこかを目次を読むことで把握します。全体を把握することで、どこから読むべきかの優先順位をつけて読む場所を決定することが出来ます。

==== 興味のある部分だけを読む
「通読しよう」「一字一句読もう」という読み方への強迫観念が読書の難易度を上げます。
技術書を読む目的は知識を得ることであり、通読して全てを読むことが目的ではありません。
読書は興味のある部分だけを読み、興味のない部分を読む必要はなないです。

==== つまらない場合は読むのをやめる
つまらない、自分のレベルと合っておらず得るものがないと判断した場合は読むのをやめた方が良いです。本の値段よりも得るものがないのに読んでいる時間のほうが無駄です。
一度つまらないと感じてしまった場合、読み進めるのも苦痛になり頭にも入ってきません。


=== 読後編

==== 本は2度読む
本は2度読む。もしくはまとめたものを再度見直す。

==== アウトプットする
読むだけで読んで得たものを活用しないのはたんなる読書好きでしかありません。得たものをアウトプットし活用することに目的があり。アウトプットし考えることにより定着していきます。
[quote, ショーペンハウエル『読書について』]
____
読書とは他人に考えてもらうことである。1日を多読に費やす勤勉な人間はしだいに自分でものを考える力を失っていく。
____


=== 参考文献
